// @score/components — DSL components for Score EDM framework

export { Synth, type SynthProps, type SynthComponent } from './synth.js'
export { Sample, type SampleProps, type SampleComponent } from './sample.js'
export { Kick, type KickProps } from './kick.js'
export { Snare, type SnareProps } from './snare.js'
export { HiHat, type HiHatProps } from './hihat.js'
export { Theremin, type ThereminProps, type ThereminComponent } from './theremin.js'
export { Sax, type SaxProps, type SaxComponent } from './sax.js'
export { createKick808, type Kick808Props, type PercussionComponent } from './drums/kick808.js'
export { createKick909, type Kick909Props, type Kick909Component } from './drums/kick909.js'
export { createHihat808, createHihatOpen808, type Hihat808Props, type Hihat808Component } from './drums/hihat808.js'
export { createSnare909, type Snare909Props, type Snare909Component } from './drums/snare909.js'
export { createSubtractiveSynth, type SubtractiveSynthProps, type SubtractiveSynthComponent } from './synths/subtractive.js'
export { createFMSynth, type FMSynthProps, type FMSynthComponent, type FMSynthAmpAdsr, type FMSynthModAdsr } from './synths/fm.js'
export { createPad, type PadProps, type PadComponent } from './synths/pad.js'
export { createRhodes, type RhodesProps, type RhodesComponent } from './synths/rhodes.js'
export { createPluck, type PluckProps, type PluckComponent } from './synths/pluck.js'
export { createBass303, type Bass303Props, type Bass303Component, type Bass303AdsrProps } from './synths/bass303.js'
